export const environment = {
  production: true,
  apiBaseUrl: 'https://devgateway.hypernymbiz.com',
  fleetBaseUrl: 'https://devgateway.hypernymbiz.com/fms-fleet',
  driverBaseUrl: 'https://devgateway.hypernymbiz.com/fms-driver',
  reportsBaseUrl: 'https://devgateway.hypernymbiz.com/fms-reports',
  userMsBaseUrl: 'https://devgateway.hypernymbiz.com/user-ms',
  cobPackagesBaseUrl: 'https://devgateway.hypernymbiz.com/cob-packages',
  osrmBaseUrl: 'https://devgateway.hypernymbiz.com/osrm-pakistan',
  osrmFallbackUrl: 'https://router.project-osrm.org',
  mapLightStyleUrl: 'https://tiles.openfreemap.org/styles/liberty',
  mapDarkStyleUrl: 'https://tiles.openfreemap.org/styles/dark',
  nominatimBaseUrl: 'https://devgateway.hypernymbiz.com/nominatim-pakistan',
  useCaseId: 6,
  signalRUrl: 'https://func-stag-all.azurewebsites.net',
  notificationsUrl: 'https://devgateway.hypernymbiz.com/fms-fleet/api/notification',
  firebase: {
    apiKey: 'AIzaSyDybdUp0Ue3yuPS5XQfGMxXeBq0CzQ-cME',
    authDomain: 'fmsnewpackage.firebaseapp.com',
    databaseURL: 'https://fmsnewpackage-default-rtdb.firebaseio.com',
    projectId: 'fmsnewpackage',
    storageBucket: 'fmsnewpackage.appspot.com',
    messagingSenderId: '1076830721170',
    appId: '1:1076830721170:web:b72455693f5aa3cfd1024b',
    measurementId: 'G-FV991JH40G',
  },
} as const;
