import { TableColumn } from '@iotility/shared-ui';
import { ReportClass, ReportType } from '../../../shared/services/reports-api.service';

export interface ReportDefinition {
  type: ReportType;
  reportClass: ReportClass;
  featureId: number;
  name: string;
  description: string;
  icon: string;
  columns: TableColumn[];
  durationColumns?: string[];
  minTableWidth?: number;
}

const column = (key: string, label: string, type?: TableColumn['type']): TableColumn => ({
  key,
  label,
  ...(type ? { type } : {}),
});

export const REPORT_DEFINITIONS: readonly ReportDefinition[] = [
  {
    type: 'journey_report',
    reportClass: 'fleet',
    featureId: 500,
    name: 'Journey',
    description: 'Ignition-to-ignition vehicle journeys',
    icon: 'JR',
    minTableWidth: 1300,
    columns: [
      column('ignition_start_time', 'Ignition Start', 'date'),
      column('start_location', 'Start Location'),
      column('odo_start_reading', 'Start Odometer'),
      column('ignition_end_time', 'Ignition End', 'date'),
      column('end_location', 'End Location'),
      column('odo_end_reading', 'End Odometer'),
      column('driver_name', 'Driver Name'),
      column('distance_travelled', 'Distance Travelled'),
    ],
  },
  {
    type: 'quick_overview_report',
    reportClass: 'fleet',
    featureId: 501,
    name: 'Quick Overview',
    description: 'Current vehicle activity overview',
    icon: 'QO',
    columns: [
      column('registration', 'Vehicle'),
      column('driver_name', 'Driver Name'),
      column('date/time', 'Date / Time'),
      column('current_location', 'Current Location'),
      column('distance_travelled', 'Distance Travelled'),
    ],
  },
  {
    type: 'geo_fence_report',
    reportClass: 'driver',
    featureId: 502,
    name: 'Geofencing Entry & Exit',
    description: 'Driver geozone entry and exit activity',
    icon: 'GF',
    columns: [
      column('vehicle_registration', 'Vehicle'),
      column('driver_name', 'Driver Name'),
      column('geo_zone_name', 'Geozone'),
      column('geo_zone_entry_time', 'Entry Time', 'date'),
      column('geo_zone_exit_time', 'Exit Time', 'date'),
    ],
  },
  {
    type: 'trip_report',
    reportClass: 'fleet',
    featureId: 503,
    name: 'Trips',
    description: 'Trip timing, distance and driving activity',
    icon: 'TR',
    minTableWidth: 1500,
    durationColumns: ['total_trip_duration', 'driving_duration', 'idle_duration', 'device_offline_duration'],
    columns: [
      column('start_location', 'Start Location'),
      column('end_location', 'End Location'),
      column('start_date_time', 'Start Time', 'date'),
      column('end_date_time', 'End Time', 'date'),
      column('total_trip_duration', 'Trip Duration'),
      column('driving_duration', 'Driving Duration'),
      column('idle_duration', 'Idle Duration'),
      column('device_offline_duration', 'Offline Duration'),
      column('driver_name', 'Driver Name'),
      column('distance_covered', 'Distance Covered'),
      column('max_speed', 'Max Speed'),
      column('odo_start_reading', 'Start Odometer'),
      column('odo_end_reading', 'End Odometer'),
    ],
  },
  {
    type: 'over_speeding_report',
    reportClass: 'fleet',
    featureId: 504,
    name: 'Over Speeding Analysis',
    description: 'Speed violations and affected journeys',
    icon: 'OS',
    minTableWidth: 1400,
    durationColumns: ['violation_duration'],
    columns: [
      column('vehicle_registration', 'Vehicle'),
      column('device_id', 'Device ID'),
      column('start_date_time', 'Start Time', 'date'),
      column('start_location', 'Start Location'),
      column('end_location', 'End Location'),
      column('end_date_time', 'End Time', 'date'),
      column('violation_duration', 'Violation Duration'),
      column('initial_speed', 'Initial Speed'),
      column('max_speed_violation', 'Maximum Speed'),
      column('speed_threshold', 'Speed Threshold'),
      column('driver_name', 'Driver Name'),
      column('distance_travelled', 'Distance Travelled'),
    ],
  },
  {
    type: 'vehicle_utilisation_extended_report',
    reportClass: 'fleet',
    featureId: 505,
    name: 'Vehicle Utilisation',
    description: 'Extended vehicle usage and productivity',
    icon: 'VU',
    minTableWidth: 1200,
    durationColumns: ['total_power_on_duration', 'total_motion_duration', 'motion_duration_per_day'],
    columns: [
      column('vehicle_registration', 'Vehicle'),
      column('device_id', 'Device ID'),
      column('days_used', 'Days Used'),
      column('total_distance_travelled', 'Total Distance'),
      column('total_power_on_duration', 'Powered On'),
      column('total_motion_duration', 'Motion Duration'),
      column('motion_duration_per_day', 'Motion / Day'),
      column('distance_travelled_per_day', 'Distance / Day'),
      column('trip_per_day', 'Trips / Day'),
      column('usage_per_day', 'Usage / Day'),
    ],
  },
  {
    type: 'events_report',
    reportClass: 'fleet',
    featureId: 506,
    name: 'Events',
    description: 'Vehicle violations and generated events',
    icon: 'EV',
    columns: [
      column('vehicle_registration', 'Vehicle'),
      column('violation_type', 'Violation Type'),
      column('event_generation_time', 'Event Time', 'date'),
      column('location', 'Location'),
      column('driver_name', 'Driver Name'),
    ],
  },
  {
    type: 'driver_score_card_report',
    reportClass: 'driver',
    featureId: 507,
    name: 'Driver Scorecard',
    description: 'Driver performance and safety indicators',
    icon: 'DS',
    minTableWidth: 900,
    columns: [
      column('driver_name', 'Driver Name'),
      column('vehicle_id', 'Vehicle'),
      column('total_jobs', 'Total Jobs'),
      column('total_distance', 'Total Distance'),
      column('over_speeding', 'Over Speeding'),
      column('harsh_braking', 'Harsh Braking'),
      column('harsh_acceleration', 'Harsh Acceleration'),
    ],
  },
  {
    type: 'excessive_idling_report',
    reportClass: 'driver',
    featureId: 508,
    name: 'Excessive Idling',
    description: 'Driver and vehicle idle-time events',
    icon: 'EI',
    durationColumns: ['total_idle_time'],
    columns: [
      column('vehicle_registration', 'Vehicle'),
      column('driver_name', 'Driver Name'),
      column('location', 'Location'),
      column('total_idle_time', 'Total Idle Time'),
      column('start_time', 'Start Time', 'date'),
      column('end_time', 'End Time', 'date'),
    ],
  },
  {
    type: 'qpmc_yard_utilization_report',
    reportClass: 'fleet',
    featureId: 512,
    name: 'Yard Utilization',
    description: 'Vehicle productivity and efficiency',
    icon: 'YU',
    minTableWidth: 1100,
    durationColumns: ['powered_on', 'idle_time', 'traveling_time', 'productive_time'],
    columns: [
      column('vehicle_registration', 'Vehicle'),
      column('report_date', 'Report Date', 'date'),
      column('powered_on', 'Powered On'),
      column('idle_time', 'Idle Time'),
      column('traveling_time', 'Travelling Time'),
      column('productive_time', 'Productive Time'),
      column('loading_cycles', 'Loading Cycles'),
      column('efficiency_ratio', 'Efficiency Ratio'),
      column('distance_travelled', 'Distance Travelled'),
    ],
  },
  {
    type: 'qpmc_loading_activity_report',
    reportClass: 'fleet',
    featureId: 512,
    name: 'Loading Activity',
    description: 'Loading events and durations',
    icon: 'LA',
    durationColumns: ['loading_duration'],
    columns: [
      column('vehicle_registration', 'Vehicle'),
      column('driver_name', 'Driver Name'),
      column('location', 'Location'),
      column('loading_duration', 'Loading Duration'),
      column('start_time', 'Start Time', 'date'),
      column('end_time', 'End Time', 'date'),
    ],
  },
  {
    type: 'qpmc_engine_health_report',
    reportClass: 'fleet',
    featureId: 512,
    name: 'Engine Health',
    description: 'Engine breaches and thresholds',
    icon: 'EH',
    columns: [
      column('vehicle_registration', 'Vehicle'),
      column('breach_type', 'Breach Type'),
      column('value', 'Value'),
      column('threshold', 'Threshold'),
      column('location', 'Location'),
    ],
  },
  {
    type: 'qpmc_device_health_report',
    reportClass: 'fleet',
    featureId: 512,
    name: 'Device Health',
    description: 'Reporting gaps and device availability',
    icon: 'DH',
    durationColumns: ['gap_duration'],
    columns: [
      column('gap_start', 'Gap Start', 'date'),
      column('gap_duration', 'Gap Duration'),
      column('report_date', 'Report Date', 'date'),
      column('vehicle_registration', 'Vehicle'),
    ],
  },
  {
    type: 'qpmc_network_coverage_report',
    reportClass: 'fleet',
    featureId: 512,
    name: 'Network & GPS Coverage',
    description: 'Signal strength and GPS availability',
    icon: 'NC',
    columns: [
      column('avg_rssi', 'Average RSSI'),
      column('weak_signal_pct', 'Weak Signal %'),
      column('no_fix_pct', 'No GPS Fix %'),
      column('report_date', 'Report Date', 'date'),
    ],
  },
  {
    type: 'qpmc_eye_sensor_health_report',
    reportClass: 'fleet',
    featureId: 512,
    name: 'Eye Sensor Health',
    description: 'Sensor status and reporting health',
    icon: 'SH',
    columns: [
      column('status', 'Status'),
      column('reporting_pct', 'Reporting %'),
      column('cycles_counted', 'Cycles Counted'),
      column('sensor', 'Sensor'),
    ],
  },
  {
    type: 'qpmc_after_hours_usage_report',
    reportClass: 'fleet',
    featureId: 512,
    name: 'After-Hours Usage',
    description: 'Equipment activity outside working hours',
    icon: 'AH',
    columns: [
      column('reason', 'Reason'),
      column('start_time', 'Start Time', 'date'),
      column('driver_name', 'Driver Name'),
      column('vehicle_registration', 'Vehicle'),
    ],
  },
  {
    type: 'qpmc_fleet_right_sizing_report',
    reportClass: 'fleet',
    featureId: 512,
    name: 'Fleet Right-Sizing',
    description: 'Utilization and fleet capacity insights',
    icon: 'FR',
    columns: [
      column('efficiency_ratio', 'Efficiency Ratio'),
      column('utilization_band', 'Utilization Band'),
      column('days_active', 'Days Active'),
      column('loading_cycles', 'Loading Cycles'),
    ],
  },
];
