import { DropdownOption } from '@iotility/shared-ui';
export interface ViolationRecord { id:string;type:string;category:string;severity:string;source:string;driver:string;vehicle:string;fleet:string;location:string;timestamp:string;speed:string;review:string;fine:number;fineStatus:string;scoreImpact:number;description:string; }
export const VIOLATIONS:ViolationRecord[]=[
  {id:'VIO-2048',type:'Critical Speeding',category:'Speeding',severity:'Critical',source:'Telematics',driver:'James Hartley',vehicle:'LP-4821',fleet:'London Delivery Fleet',location:'M1 Northbound, J14',timestamp:'24 Jul 2026 · 14:28',speed:'94 / 70 mph',review:'Pending',fine:320,fineStatus:'Pending',scoreImpact:-12,description:'Vehicle exceeded the configured critical speed threshold for 42 seconds.'},
  {id:'VIO-2047',type:'Mobile Phone Use',category:'Safety',severity:'High',source:'DashCam',driver:'Thomas Griffiths',vehicle:'LP-6612',fleet:'Northern Distribution',location:'Trafford Park, Manchester',timestamp:'24 Jul 2026 · 12:06',speed:'—',review:'Confirmed',fine:200,fineStatus:'Pending',scoreImpact:-10,description:'DashCam review detected handheld mobile-phone use while driving.'},
  {id:'VIO-2046',type:'Harsh Braking',category:'Behaviour',severity:'Medium',source:'Telematics',driver:'Oliver Pemberton',vehicle:'LP-3312',fleet:'London Delivery Fleet',location:'A40 Westbound, London',timestamp:'24 Jul 2026 · 10:42',speed:'48 mph',review:'Reviewed',fine:0,fineStatus:'No Fine',scoreImpact:-4,description:'Deceleration exceeded the configured harsh-braking threshold.'},
  {id:'VIO-2045',type:'Exclusion Zone Entry',category:'Geozone',severity:'High',source:'Telematics',driver:'Priya Sharma',vehicle:'LP-5531',fleet:'Midlands Operations',location:'London Low Emission Zone',timestamp:'23 Jul 2026 · 18:15',speed:'22 mph',review:'Confirmed',fine:180,fineStatus:'Paid',scoreImpact:-8,description:'Vehicle entered an active exclusion zone without authorisation.'},
  {id:'VIO-2044',type:'Seatbelt Violation',category:'Safety',severity:'Critical',source:'DashCam',driver:'Aisha Okonkwo',vehicle:'LP-2201',fleet:'Midlands Operations',location:'Birmingham Ring Road',timestamp:'23 Jul 2026 · 16:38',speed:'36 mph',review:'Pending',fine:260,fineStatus:'Disputed',scoreImpact:-14,description:'Seatbelt was not detected while the vehicle was moving.'},
  {id:'VIO-2043',type:'Extended Idling',category:'Behaviour',severity:'Low',source:'Telematics',driver:'Sarah Whitfield',vehicle:'LP-2244',fleet:'Northern Distribution',location:'Salford Business Park',timestamp:'23 Jul 2026 · 11:20',speed:'0 mph',review:'Reviewed',fine:0,fineStatus:'No Fine',scoreImpact:-2,description:'Engine remained running while stationary beyond the fleet limit.'},
  {id:'VIO-2041',type:'Harsh Cornering',category:'Behaviour',severity:'Medium',source:'Telematics',driver:'Mohammed Al-Rashid',vehicle:'LP-7734',fleet:'Northern Distribution',location:'Aston Expressway',timestamp:'21 Jul 2026 · 15:52',speed:'41 mph',review:'Reviewed',fine:0,fineStatus:'No Fine',scoreImpact:-4,description:'Lateral g-force exceeded the fleet harsh-cornering threshold.'},
];
export const CATEGORY_OPTIONS:DropdownOption[]=[{id:'all',label:'All Categories'},...['Speeding','Behaviour','Safety','Compliance','Geozone'].map(label=>({id:label,label}))];
export const SEVERITY_OPTIONS:DropdownOption[]=[{id:'all',label:'All Severity'},...['Critical','High','Medium','Low'].map(label=>({id:label,label}))];
export const SOURCE_OPTIONS:DropdownOption[]=[{id:'all',label:'All Sources'},...['Telematics','DashCam','Manual'].map(label=>({id:label,label}))];
