import { Component, OnInit, computed, signal } from '@angular/core';
import { BlockingLoader, DataTable, TableAction, TableColumn, TableRow } from '@iotility/shared-ui';
import { finalize } from 'rxjs';
import { DriverApiService, DriverManager } from '../../../shared/services/driver-api.service';
import { FeedbackDialogBridgeService } from '../../../shared/services/feedback-dialog-bridge.service';
import { ManagerForm } from '../manager-form/manager-form';

@Component({selector:'app-manager-list',imports:[BlockingLoader,DataTable,ManagerForm],templateUrl:'./manager-list.html',styleUrl:'../drivers-page.css'})
export class ManagerList implements OnInit{
  private searchTimer?:ReturnType<typeof setTimeout>;protected readonly loading=signal(true);protected readonly actionLoading=signal(false);protected readonly error=signal('');protected readonly records=signal<DriverManager[]>([]);protected readonly total=signal(0);protected readonly offset=signal(0);protected readonly search=signal('');protected readonly limit=10;protected readonly formOpen=signal(false);protected readonly selected=signal<DriverManager|null>(null);protected readonly actions:TableAction[]=['edit','delete'];
  protected readonly columns:TableColumn[]=[{key:'name',label:'Manager',type:'user',secondaryKey:'employeeId'},{key:'rfidTag',label:'Tag ID'},{key:'modifiedBy',label:'Modified By'},{key:'updatedAt',label:'Modified Date',type:'date'},{key:'createdAt',label:'Created Date',type:'date'},{key:'actions',label:'Actions',type:'actions'}];
  protected readonly rows=computed<TableRow[]>(()=>this.records().map(m=>({id:m.id,name:m.name||'Unnamed manager',employeeId:m.employee_id||'No employee ID',rfidTag:m.rfid_tag||'Not assigned',modifiedBy:m.modified_by||'Not available',updatedAt:this.date(m.updated_at),createdAt:this.date(m.created_at),actions:''})));protected readonly start=computed(()=>this.total()?this.offset()+1:0);protected readonly end=computed(()=>Math.min(this.offset()+this.limit,this.total()));
  constructor(private readonly api:DriverApiService,private readonly feedback:FeedbackDialogBridgeService){}ngOnInit():void{this.load();}protected searchChanged(v:string):void{this.search.set(v);clearTimeout(this.searchTimer);this.searchTimer=setTimeout(()=>{this.offset.set(0);this.load();},400);}protected previous():void{this.offset.update(v=>Math.max(0,v-this.limit));this.load();}protected next():void{if(this.offset()+this.limit<this.total()){this.offset.update(v=>v+this.limit);this.load();}}protected openCreate():void{this.selected.set(null);this.formOpen.set(true);}protected close():void{this.formOpen.set(false);this.selected.set(null);}protected saved():void{this.close();this.offset.set(0);this.load();}protected action(e:{action:TableAction;row:TableRow}):void{const m=this.records().find(x=>x.id===Number(e.row['id']));if(!m)return;if(e.action==='edit'){this.selected.set(m);this.formOpen.set(true);}else if(e.action==='delete')void this.remove(m);}protected load():void{this.loading.set(true);this.error.set('');this.api.getManagers(this.limit,this.offset(),this.search().trim()).pipe(finalize(()=>this.loading.set(false))).subscribe({next:r=>{this.records.set(r.data?.data??[]);this.total.set(r.data?.count??0);},error:r=>this.error.set(r.error?.message||'Managers could not be loaded.')});}private date(v:string):string{return v?v.slice(0,10):'Not available';}private async remove(m:DriverManager):Promise<void>{if(!await this.feedback.open({type:'warning',title:'Delete manager?',message:`${m.name} will be permanently deleted.`,confirmText:'Delete manager',cancelText:'Keep manager',showCancel:true}))return;this.actionLoading.set(true);this.api.deleteManager(m.id).subscribe({next:async()=>{this.actionLoading.set(false);await this.feedback.open({type:'success',title:'Manager deleted',message:`${m.name} was deleted successfully.`,confirmText:'Done',showCancel:false});this.load();},error:r=>{this.actionLoading.set(false);const x=r.error?.message||'Manager could not be deleted.';void this.feedback.open({type:'error',title:'Unable to delete manager',message:x,confirmText:'Close',showCancel:false});}});}
}
