// src/pages/fleetpoint/operations/ViolationsPage.tsx
// Violations management — All Violations, Fines & Penalties, Configuration
//
// DEVELOPER NOTES:
// ─────────────────────────────────────────────────────────────────────────────
// THREE VIOLATION SOURCES — unified in one page:
//
// 1. TELEMATICS (auto-generated by backend)
//    Server checks GPS pings against violation_config thresholds
//    When speed > speedViolationKph → creates violation record automatically
//    TODO: Build threshold checker in telematics processing pipeline
//    Triggered on every GPS ping via: POST /api/internal/check-violations
//
// 2. DASHCAM (auto-generated when reviewed)
//    Fleet manager marks dashcam event as 'violation' in DashCam module
//    PATCH /api/fleetpoint/dashcam/events/:id/review → { status: 'violation' }
//    Backend auto-creates violation record with dashcamEventId FK
//    dashcamEventId links back to BSJ IOT footage
//
// 3. MANUAL (fleet manager raises directly)
//    POST /api/fleetpoint/violations with source: 'manual'
//    Used for: authority fines, MOT/licence issues, unauthorised use
//
// VIOLATION CONFIG:
// Thresholds stored per fleet in violation_config table
// Fleet config overrides global config
// TODO: PUT /api/fleetpoint/violations/config to save config changes
//       Frontend sends updated violationConfig object
//       Backend validates and stores per fleet
//       Telematics pipeline reads config on startup + caches in Redis
//
// FINE MANAGEMENT:
// fineStatus: none → pending → paid | disputed | appealed
// PATCH /api/fleetpoint/violations/:id/fine { status, paidAt, receipt }
//
// EXPORT:
// GET /api/fleetpoint/violations/export?format=pdf&fleetId=&driverId=&dateFrom=&dateTo=
// GET /api/fleetpoint/violations/export?format=xlsx
// Backend generates file and returns download URL
//
// MAP:
// Violations plotted as CircleMarkers color-coded by category
// Click marker → shows violation popup with full details
// ─────────────────────────────────────────────────────────────────────────────

import { useState } from 'react'
import { MapContainer, TileLayer, CircleMarker, Popup } from 'react-leaflet'
import 'leaflet/dist/leaflet.css'
import {
  Search, Filter, Download, Plus, AlertTriangle,
  CheckCircle, Clock, X, Eye, Edit, Flag,
  ChevronDown, ChevronUp, Shield, Zap, Car,
  FileText, Settings, ToggleLeft, ToggleRight,
  Camera, Cpu, User, DollarSign
} from 'lucide-react'
import FleetpointLayout from '../../../layouts/FleetpointLayout'
import { violations, violationConfigs, fleets, drivers } from '../../../data/fleetData'
import { useTheme } from '../../../hooks/useTheme'
import type {
  Violation, ViolationSource, ViolationCategory,
  ViolationSeverity, FineStatus, ViolationConfig
} from '../../../data/fleetData'

// ─── Config ───────────────────────────────────────────────────────────────────
const CATEGORY_CONFIG: Record<ViolationCategory, {
  label: string; color: string; bg: string; border: string; mapColor: string; icon: any
}> = {
  speed:      { label: 'Speeding',    color: 'text-red-700',    bg: 'bg-red-50',    border: 'border-red-200',    mapColor: '#dc2626', icon: Zap },
  behaviour:  { label: 'Behaviour',   color: 'text-amber-700',  bg: 'bg-amber-50',  border: 'border-amber-200',  mapColor: '#d97706', icon: Car },
  safety:     { label: 'Safety',      color: 'text-orange-700', bg: 'bg-orange-50', border: 'border-orange-200', mapColor: '#ea580c', icon: Shield },
  compliance: { label: 'Compliance',  color: 'text-purple-700', bg: 'bg-purple-50', border: 'border-purple-200', mapColor: '#7c3aed', icon: FileText },
  geozone:    { label: 'Geozone',     color: 'text-blue-700',   bg: 'bg-blue-50',   border: 'border-blue-200',   mapColor: '#2563eb', icon: Flag },
}

const SEVERITY_CONFIG: Record<ViolationSeverity, {
  label: string; color: string; bg: string; border: string; dot: string
}> = {
  critical: { label: 'Critical', color: 'text-red-700',    bg: 'bg-red-50',    border: 'border-red-300',    dot: 'bg-red-500' },
  high:     { label: 'High',     color: 'text-orange-700', bg: 'bg-orange-50', border: 'border-orange-300', dot: 'bg-orange-500' },
  medium:   { label: 'Medium',   color: 'text-amber-700',  bg: 'bg-amber-50',  border: 'border-amber-300',  dot: 'bg-amber-400' },
  low:      { label: 'Low',      color: 'text-blue-700',   bg: 'bg-blue-50',   border: 'border-blue-300',   dot: 'bg-blue-400' },
}

const SOURCE_CONFIG: Record<ViolationSource, {
  label: string; color: string; bg: string; icon: any
}> = {
  telematics: { label: 'Telematics', color: 'text-purple-700', bg: 'bg-purple-50', icon: Cpu },
  dashcam:    { label: 'DashCam',    color: 'text-blue-700',   bg: 'bg-blue-50',   icon: Camera },
  manual:     { label: 'Manual',     color: 'text-gray-700',   bg: 'bg-gray-100',  icon: User },
}

const FINE_STATUS_CONFIG: Record<FineStatus, {
  label: string; color: string; bg: string
}> = {
  none:     { label: 'No Fine',  color: 'text-gray-500',   bg: 'bg-gray-50' },
  pending:  { label: 'Pending',  color: 'text-amber-700',  bg: 'bg-amber-50' },
  paid:     { label: 'Paid',     color: 'text-green-700',  bg: 'bg-green-50' },
  disputed: { label: 'Disputed', color: 'text-red-700',    bg: 'bg-red-50' },
  appealed: { label: 'Appealed', color: 'text-blue-700',   bg: 'bg-blue-50' },
}

type TabId = 'violations' | 'fines' | 'config'
type SortField = 'timestamp' | 'severity' | 'driver' | 'vehicle' | 'type'

export default function ViolationsPage() {
  const { isDark } = useTheme()
  const [activeTab, setActiveTab] = useState<TabId>('violations')
  const [search, setSearch] = useState('')
  const [filterCategory, setFilterCategory] = useState<'all' | ViolationCategory>('all')
  const [filterSeverity, setFilterSeverity] = useState<'all' | ViolationSeverity>('all')
  const [filterSource, setFilterSource] = useState<'all' | ViolationSource>('all')
  const [filterFleet, setFilterFleet] = useState('all')
  const [filterReview, setFilterReview] = useState('all')
  const [dateRange, setDateRange] = useState('month')
  const [sortField, setSortField] = useState<SortField>('timestamp')
  const [sortDir, setSortDir] = useState<'asc' | 'desc'>('desc')
  const [selectedViolation, setSelectedViolation] = useState<Violation | null>(null)
  const [selectedMapViolation, setSelectedMapViolation] = useState<Violation | null>(null)
  const [showCreateModal, setShowCreateModal] = useState(false)
  const [activeConfigFleet, setActiveConfigFleet] = useState('')
  const [showFilters, setShowFilters] = useState(false)

  // ── KPIs ────────────────────────────────────────────────────────────────────
  const total = violations.length
  const critical = violations.filter(v => v.severity === 'critical').length
  const pending = violations.filter(v => v.reviewStatus === 'pending').length
  const finesPending = violations.filter(v => v.fineStatus === 'pending').length
  const totalFines = violations.reduce((a, v) => a + v.fineAmount, 0)
  const totalScoreImpact = violations.reduce((a, v) => a + v.scoreImpact, 0)

  // ── Filtered ────────────────────────────────────────────────────────────────
  const filtered = violations
    .filter(v => {
      const s = search.toLowerCase()
      const matchSearch = !search ||
        v.vehiclePlate.toLowerCase().includes(s) ||
        v.driverName.toLowerCase().includes(s) ||
        v.type.toLowerCase().includes(s) ||
        v.location.toLowerCase().includes(s)
      const matchCat = filterCategory === 'all' || v.category === filterCategory
      const matchSev = filterSeverity === 'all' || v.severity === filterSeverity
      const matchSrc = filterSource === 'all' || v.source === filterSource
      const matchFleet = filterFleet === 'all' || v.fleetId === filterFleet
      const matchRev = filterReview === 'all' || v.reviewStatus === filterReview
      return matchSearch && matchCat && matchSev && matchSrc && matchFleet && matchRev
    })
    .sort((a, b) => {
      let aVal: any, bVal: any
      switch (sortField) {
        case 'timestamp': aVal = a.timestamp; bVal = b.timestamp; break
        case 'severity': aVal = a.severity; bVal = b.severity; break
        case 'driver': aVal = a.driverName; bVal = b.driverName; break
        case 'vehicle': aVal = a.vehiclePlate; bVal = b.vehiclePlate; break
        case 'type': aVal = a.type; bVal = b.type; break
        default: aVal = a.timestamp; bVal = b.timestamp
      }
      return sortDir === 'asc'
        ? String(aVal).localeCompare(String(bVal))
        : String(bVal).localeCompare(String(aVal))
    })

  const toggleSort = (field: SortField) => {
    if (sortField === field) setSortDir(d => d === 'asc' ? 'desc' : 'asc')
    else { setSortField(field); setSortDir('desc') }
  }

  const SortIcon = ({ field }: { field: SortField }) => (
    <span className="ml-1 inline-flex flex-col">
      <ChevronUp size={10} className={sortField === field && sortDir === 'asc' ? 'text-purple-600' : 'text-gray-300'} />
      <ChevronDown size={10} className={sortField === field && sortDir === 'desc' ? 'text-purple-600' : 'text-gray-300'} />
    </span>
  )

  // Active config
  const activeConfig = violationConfigs.find(c => c.fleetId === activeConfigFleet)
    || violationConfigs[0]

  const tabs: { id: TabId; label: string; emoji: string; count?: number }[] = [
    { id: 'violations', label: 'All Violations', emoji: '⚠️', count: total },
    { id: 'fines',      label: 'Fines & Penalties', emoji: '💰', count: finesPending },
    { id: 'config',     label: 'Configuration', emoji: '⚙️' },
  ]

  return (
    <FleetpointLayout>
      <div className={`p-6 min-h-full ${isDark ? 'bg-gray-950' : 'bg-gray-50'}`}>

        {/* Header */}
        <div className="flex items-center justify-between mb-5">
          <div>
            <h1 className={`text-xl font-bold ${isDark ? 'text-white' : 'text-gray-900'}`}>Violations</h1>
            <p className={`text-sm mt-0.5 ${isDark ? 'text-gray-400' : 'text-gray-500'}`}>
              {total} violations · {critical} critical · {pending} pending review · £{totalFines.toLocaleString()} in fines
            </p>
          </div>
          <div className="flex items-center gap-2">
            <button className={`flex items-center gap-2 text-sm px-3 py-2 rounded-xl border transition-colors
              ${isDark ? 'border-gray-700 text-gray-300 hover:bg-gray-800' : 'border-gray-200 text-gray-600 hover:bg-gray-50'}`}>
              <Download size={15} /> Export XLS
            </button>
            <button className={`flex items-center gap-2 text-sm px-3 py-2 rounded-xl border transition-colors
              ${isDark ? 'border-gray-700 text-gray-300 hover:bg-gray-800' : 'border-gray-200 text-gray-600 hover:bg-gray-50'}`}>
              <Download size={15} /> Export PDF
            </button>
            <button onClick={() => setShowCreateModal(true)}
              className="flex items-center gap-2 bg-purple-600 hover:bg-purple-700 text-white text-sm font-semibold px-4 py-2 rounded-xl transition-colors">
              <Plus size={15} /> Add Manual Violation
            </button>
          </div>
        </div>

        {/* KPI strip */}
        <div className="grid grid-cols-6 gap-3 mb-5">
          {[
            { label: 'Total', value: total, color: 'text-gray-600', bg: 'bg-gray-100', icon: AlertTriangle,
              onClick: () => setFilterSeverity('all') },
            { label: 'Critical', value: critical, color: 'text-red-600', bg: 'bg-red-50', icon: AlertTriangle,
              onClick: () => setFilterSeverity('critical') },
            { label: 'Pending Review', value: pending, color: 'text-amber-600', bg: 'bg-amber-50', icon: Clock,
              onClick: () => setFilterReview('pending') },
            { label: 'Fines Pending', value: finesPending, color: 'text-orange-600', bg: 'bg-orange-50', icon: DollarSign,
              onClick: () => setActiveTab('fines') },
            { label: 'Total Fines', value: `£${totalFines.toLocaleString()}`, color: 'text-purple-600', bg: 'bg-purple-50', icon: FileText,
              onClick: () => {} },
            { label: 'Score Impact', value: totalScoreImpact, color: 'text-red-600', bg: 'bg-red-50', icon: Zap,
              onClick: () => {} },
          ].map((kpi, i) => (
            <button key={i} onClick={kpi.onClick}
              className={`border rounded-2xl p-3 text-left transition-all hover:shadow-md
                ${isDark ? 'bg-gray-800 border-gray-700' : 'bg-white border-gray-200'}`}>
              <div className={`w-7 h-7 rounded-lg ${kpi.bg} flex items-center justify-center mb-2`}>
                <kpi.icon size={14} className={kpi.color} />
              </div>
              <p className={`text-xl font-bold ${isDark ? 'text-white' : 'text-gray-900'}`}>{kpi.value}</p>
              <p className={`text-xs ${isDark ? 'text-gray-400' : 'text-gray-500'}`}>{kpi.label}</p>
            </button>
          ))}
        </div>

        {/* Tabs */}
        <div className={`flex items-center gap-1 mb-5 border-b ${isDark ? 'border-gray-700' : 'border-gray-200'}`}>
          {tabs.map(tab => (
            <button key={tab.id} onClick={() => setActiveTab(tab.id)}
              className={`flex items-center gap-1.5 px-4 py-2.5 text-xs font-medium border-b-2 -mb-px transition-all
                ${activeTab === tab.id
                  ? 'border-purple-600 text-purple-600'
                  : `border-transparent ${isDark ? 'text-gray-400 hover:text-gray-200' : 'text-gray-500 hover:text-gray-700'}`}`}>
              <span>{tab.emoji}</span>
              {tab.label}
              {tab.count !== undefined && tab.count > 0 && (
                <span className={`text-xs font-bold px-1.5 py-0.5 rounded-full
                  ${activeTab === tab.id ? 'bg-purple-100 text-purple-700' : `${isDark ? 'bg-gray-700 text-gray-300' : 'bg-gray-100 text-gray-500'}`}`}>
                  {tab.count}
                </span>
              )}
            </button>
          ))}
        </div>

        {/* ── ALL VIOLATIONS TAB ────────────────────────────────────────────── */}
        {activeTab === 'violations' && (
          <>
            {/* Date range + search + filters */}
            <div className={`rounded-2xl border p-4 mb-4 ${isDark ? 'bg-gray-800 border-gray-700' : 'bg-white border-gray-200'}`}>
              <div className="flex items-center gap-3 mb-3">
                {/* Date range */}
                <div className={`flex rounded-xl border overflow-hidden ${isDark ? 'border-gray-700' : 'border-gray-200'}`}>
                  {[
                    { id: 'today', label: 'Today' },
                    { id: 'week', label: 'This Week' },
                    { id: 'month', label: 'This Month' },
                  ].map(d => (
                    <button key={d.id} onClick={() => setDateRange(d.id)}
                      className={`px-3 py-2 text-xs font-medium transition-colors
                        ${dateRange === d.id
                          ? 'bg-purple-600 text-white'
                          : `${isDark ? 'bg-gray-800 text-gray-400' : 'bg-white text-gray-500'}`}`}>
                      {d.label}
                    </button>
                  ))}
                </div>

                {/* Search */}
                <div className={`flex-1 flex items-center gap-2 border rounded-xl px-3 py-2
                  ${isDark ? 'border-gray-700 bg-gray-900' : 'border-gray-200 bg-gray-50'}`}>
                  <Search size={14} className="text-gray-400 shrink-0" />
                  <input type="text" placeholder="Search plate, driver, violation type, location..."
                    value={search} onChange={e => setSearch(e.target.value)}
                    className={`flex-1 text-sm outline-none bg-transparent
                      ${isDark ? 'text-white placeholder-gray-500' : 'text-gray-900 placeholder-gray-400'}`} />
                  {search && <button onClick={() => setSearch('')}><X size={12} className="text-gray-400" /></button>}
                </div>

                <button onClick={() => setShowFilters(!showFilters)}
                  className={`flex items-center gap-2 text-sm px-3 py-2 rounded-xl border transition-colors
                    ${showFilters ? 'border-purple-500 bg-purple-50 text-purple-600'
                      : `${isDark ? 'border-gray-700 text-gray-300' : 'border-gray-200 text-gray-600'}`}`}>
                  <Filter size={14} /> Filters
                </button>
              </div>

              {showFilters && (
                <div className="flex items-center gap-3 flex-wrap">
                  {[
                    {
                      label: 'Category', value: filterCategory,
                      onChange: (v: string) => setFilterCategory(v as any),
                      options: [{ value: 'all', label: 'All Categories' },
                        ...Object.entries(CATEGORY_CONFIG).map(([v, c]) => ({ value: v, label: c.label }))]
                    },
                    {
                      label: 'Severity', value: filterSeverity,
                      onChange: (v: string) => setFilterSeverity(v as any),
                      options: [{ value: 'all', label: 'All Severity' },
                        ...Object.entries(SEVERITY_CONFIG).map(([v, c]) => ({ value: v, label: c.label }))]
                    },
                    {
                      label: 'Source', value: filterSource,
                      onChange: (v: string) => setFilterSource(v as any),
                      options: [{ value: 'all', label: 'All Sources' },
                        ...Object.entries(SOURCE_CONFIG).map(([v, c]) => ({ value: v, label: c.label }))]
                    },
                    {
                      label: 'Fleet', value: filterFleet,
                      onChange: (v: string) => setFilterFleet(v),
                      options: [{ value: 'all', label: 'All Fleets' },
                        ...fleets.map(f => ({ value: f.id, label: f.name }))]
                    },
                    {
                      label: 'Review', value: filterReview,
                      onChange: (v: string) => setFilterReview(v),
                      options: [
                        { value: 'all', label: 'All Status' },
                        { value: 'pending', label: 'Pending Review' },
                        { value: 'reviewed', label: 'Reviewed' },
                        { value: 'closed', label: 'Closed' },
                      ]
                    },
                  ].map(f => (
                    <select key={f.label} value={f.value} onChange={e => f.onChange(e.target.value)}
                      className={`text-sm border rounded-xl px-3 py-2 outline-none
                        ${isDark ? 'bg-gray-700 border-gray-600 text-white' : 'bg-white border-gray-200 text-gray-700'}`}>
                      {f.options.map(o => <option key={o.value} value={o.value}>{o.label}</option>)}
                    </select>
                  ))}
                  <button onClick={() => {
                    setFilterCategory('all'); setFilterSeverity('all');
                    setFilterSource('all'); setFilterFleet('all');
                    setFilterReview('all'); setSearch('')
                  }} className="text-xs text-purple-600 hover:underline">Clear all</button>
                </div>
              )}
            </div>

            {/* Map + List */}
            <div className="grid grid-cols-5 gap-4">

              {/* Map — 2 cols */}
              <div className={`col-span-2 rounded-2xl border overflow-hidden ${isDark ? 'bg-gray-800 border-gray-700' : 'bg-white border-gray-200'}`}
                style={{ height: '520px' }}>
                <div className={`flex items-center justify-between px-4 py-3 border-b ${isDark ? 'border-gray-700' : 'border-gray-200'}`}>
                  <span className={`text-sm font-semibold ${isDark ? 'text-white' : 'text-gray-900'}`}>
                    Violation Map
                  </span>
                  <span className={`text-xs ${isDark ? 'text-gray-400' : 'text-gray-500'}`}>
                    {filtered.length} shown
                  </span>
                </div>
                {/* Legend */}
                <div className={`px-3 py-2 border-b flex flex-wrap gap-2 ${isDark ? 'border-gray-700' : 'border-gray-100'}`}>
                  {Object.entries(CATEGORY_CONFIG).map(([cat, cfg]) => (
                    <div key={cat} className="flex items-center gap-1">
                      <div className="w-2.5 h-2.5 rounded-full" style={{ background: cfg.mapColor }}></div>
                      <span className={`text-xs ${isDark ? 'text-gray-400' : 'text-gray-500'}`}>{cfg.label}</span>
                    </div>
                  ))}
                </div>
                <div style={{ height: 'calc(520px - 88px)' }}>
                  <MapContainer center={[52.5, -1.5]} zoom={6}
                    style={{ height: '100%', width: '100%' }}>
                    <TileLayer
                      attribution='&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>'
                      url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
                    />
                    {filtered.map(v => {
                      const cat = CATEGORY_CONFIG[v.category]
                      const isSelected = selectedMapViolation?.id === v.id
                      return (
                        <CircleMarker key={v.id}
                          center={[v.lat, v.lng]}
                          radius={isSelected ? 10 : 7}
                          pathOptions={{
                            color: cat.mapColor,
                            fillColor: cat.mapColor,
                            fillOpacity: isSelected ? 0.9 : 0.7,
                            weight: isSelected ? 3 : 1.5,
                          }}
                          eventHandlers={{
                            click: () => {
                              setSelectedMapViolation(v)
                              setSelectedViolation(v)
                            }
                          }}>
                          <Popup>
                            <div style={{ fontSize: 11, minWidth: 180 }}>
                              <p style={{ fontWeight: 700, marginBottom: 4 }}>{v.type}</p>
                              <p style={{ color: '#6b7280', marginBottom: 2 }}>
                                🚛 {v.vehiclePlate} · {v.driverName}
                              </p>
                              <p style={{ color: '#6b7280', marginBottom: 2 }}>
                                🕐 {new Date(v.timestamp).toLocaleString('en-GB', { day: 'numeric', month: 'short', hour: '2-digit', minute: '2-digit' })}
                              </p>
                              <p style={{ color: '#6b7280', marginBottom: 4 }}>📍 {v.location}</p>
                              {v.speedKph > 0 && (
                                <p style={{ color: '#dc2626', fontWeight: 600 }}>
                                  ⚡ {v.speedKph} km/h (limit: {v.thresholdKph} km/h)
                                </p>
                              )}
                              {v.fineAmount > 0 && (
                                <p style={{ color: '#7c3aed', fontWeight: 600 }}>
                                  💰 Fine: £{v.fineAmount}
                                </p>
                              )}
                            </div>
                          </Popup>
                        </CircleMarker>
                      )
                    })}
                  </MapContainer>
                </div>
              </div>

              {/* Table — 3 cols */}
              <div className={`col-span-3 rounded-2xl border overflow-hidden flex flex-col
                ${isDark ? 'bg-gray-800 border-gray-700' : 'bg-white border-gray-200'}`}
                style={{ maxHeight: '520px' }}>
                <div className="overflow-y-auto flex-1">
                  <table className="w-full text-sm">
                    <thead className="sticky top-0 z-10">
                      <tr className={`border-b text-xs font-semibold uppercase tracking-wide
                        ${isDark ? 'border-gray-700 bg-gray-900 text-gray-400' : 'border-gray-100 bg-gray-50 text-gray-500'}`}>
                        <th className="px-3 py-3 text-left cursor-pointer" onClick={() => toggleSort('type')}>
                          Violation <SortIcon field="type" />
                        </th>
                        <th className="px-3 py-3 text-left cursor-pointer" onClick={() => toggleSort('driver')}>
                          Driver <SortIcon field="driver" />
                        </th>
                        <th className="px-3 py-3 text-left">Source</th>
                        <th className="px-3 py-3 text-left cursor-pointer" onClick={() => toggleSort('severity')}>
                          Severity <SortIcon field="severity" />
                        </th>
                        <th className="px-3 py-3 text-left">Speed</th>
                        <th className="px-3 py-3 text-left cursor-pointer" onClick={() => toggleSort('timestamp')}>
                          Time <SortIcon field="timestamp" />
                        </th>
                        <th className="px-3 py-3 text-left">Fine</th>
                        <th className="px-3 py-3 text-left">Status</th>
                      </tr>
                    </thead>
                    <tbody>
                      {filtered.map(v => {
                        const cat = CATEGORY_CONFIG[v.category]
                        const sev = SEVERITY_CONFIG[v.severity]
                        const src = SOURCE_CONFIG[v.source]
                        const fine = FINE_STATUS_CONFIG[v.fineStatus]
                        const isSelected = selectedViolation?.id === v.id
                        return (
                          <tr key={v.id}
                            onClick={() => setSelectedViolation(isSelected ? null : v)}
                            className={`border-b cursor-pointer transition-colors
                              ${isDark ? 'border-gray-700 hover:bg-gray-750' : 'border-gray-50 hover:bg-gray-50'}
                              ${isSelected ? (isDark ? 'bg-purple-900/20' : 'bg-purple-50') : ''}
                              ${v.severity === 'critical' && v.reviewStatus === 'pending'
                                ? `border-l-2 ${isDark ? 'border-l-red-500' : 'border-l-red-400'}` : ''}`}>
                            <td className="px-3 py-2.5">
                              <div className="flex items-center gap-1.5">
                                <div className={`w-6 h-6 rounded-lg ${cat.bg} flex items-center justify-center shrink-0`}>
                                  <cat.icon size={11} className={cat.color} />
                                </div>
                                <p className={`text-xs font-semibold ${isDark ? 'text-white' : 'text-gray-900'}`}>
                                  {v.type}
                                </p>
                              </div>
                              <p className={`text-xs ml-7.5 ${isDark ? 'text-gray-500' : 'text-gray-400'} truncate max-w-28`}>
                                {v.location.split(',')[0]}
                              </p>
                            </td>
                            <td className="px-3 py-2.5">
                              <div className="flex items-center gap-1.5">
                                <div className="w-5 h-5 rounded-full bg-gradient-to-br from-purple-500 to-blue-500 flex items-center justify-center text-white text-xs font-bold shrink-0">
                                  {v.driverName.split(' ').map(n => n[0]).join('').slice(0, 2)}
                                </div>
                                <div>
                                  <p className={`text-xs font-medium ${isDark ? 'text-gray-300' : 'text-gray-700'}`}>
                                    {v.driverName.split(' ')[0]}
                                  </p>
                                  <p className={`text-xs ${isDark ? 'text-purple-400' : 'text-purple-600'}`}>
                                    {v.vehiclePlate}
                                  </p>
                                </div>
                              </div>
                            </td>
                            <td className="px-3 py-2.5">
                              <div className={`flex items-center gap-1 px-1.5 py-0.5 rounded-lg w-fit ${src.bg}`}>
                                <src.icon size={10} className={src.color} />
                                <span className={`text-xs font-medium ${src.color}`}>{src.label}</span>
                              </div>
                            </td>
                            <td className="px-3 py-2.5">
                              <div className="flex items-center gap-1">
                                <div className={`w-2 h-2 rounded-full ${sev.dot}`}></div>
                                <span className={`text-xs font-medium ${sev.color}`}>{sev.label}</span>
                              </div>
                            </td>
                            <td className="px-3 py-2.5">
                              {v.speedKph > 0 ? (
                                <div>
                                  <span className={`text-xs font-bold ${v.speedKph > v.thresholdKph ? 'text-red-600' : isDark ? 'text-gray-300' : 'text-gray-700'}`}>
                                    {v.speedKph}
                                  </span>
                                  {v.thresholdKph > 0 && (
                                    <span className={`text-xs ${isDark ? 'text-gray-500' : 'text-gray-400'}`}>
                                      /{v.thresholdKph}
                                    </span>
                                  )}
                                </div>
                              ) : (
                                <span className={`text-xs ${isDark ? 'text-gray-500' : 'text-gray-400'}`}>—</span>
                              )}
                            </td>
                            <td className="px-3 py-2.5">
                              <span className={`text-xs ${isDark ? 'text-gray-400' : 'text-gray-500'}`}>
                                {new Date(v.timestamp).toLocaleTimeString('en-GB', { hour: '2-digit', minute: '2-digit' })}
                              </span>
                            </td>
                            <td className="px-3 py-2.5">
                              {v.fineAmount > 0 ? (
                                <div>
                                  <span className="text-xs font-bold text-red-600">£{v.fineAmount}</span>
                                  <p className={`text-xs ${fine.color}`}>{fine.label}</p>
                                </div>
                              ) : (
                                <span className={`text-xs ${isDark ? 'text-gray-600' : 'text-gray-300'}`}>—</span>
                              )}
                            </td>
                            <td className="px-3 py-2.5">
                              <span className={`text-xs px-2 py-0.5 rounded-full font-medium capitalize
                                ${v.reviewStatus === 'pending'
                                  ? 'bg-amber-50 text-amber-700'
                                  : v.reviewStatus === 'reviewed'
                                  ? 'bg-green-50 text-green-700'
                                  : 'bg-gray-100 text-gray-600'}`}>
                                {v.reviewStatus}
                              </span>
                            </td>
                          </tr>
                        )
                      })}
                    </tbody>
                  </table>
                </div>

                {/* Detail panel at bottom */}
                {selectedViolation && (
                  <div className={`border-t p-4 ${isDark ? 'border-gray-700 bg-gray-750' : 'border-gray-200 bg-gray-50'}`}>
                    <div className="flex items-start justify-between mb-2">
                      <div>
                        <p className={`font-bold text-sm ${isDark ? 'text-white' : 'text-gray-900'}`}>
                          {selectedViolation.type}
                        </p>
                        <p className={`text-xs ${isDark ? 'text-gray-400' : 'text-gray-500'}`}>
                          {selectedViolation.driverName} · {selectedViolation.vehiclePlate} · {selectedViolation.location}
                        </p>
                      </div>
                      <button onClick={() => setSelectedViolation(null)} className="text-gray-400 hover:text-gray-600">
                        <X size={14} />
                      </button>
                    </div>
                    <p className={`text-xs mb-3 ${isDark ? 'text-gray-300' : 'text-gray-700'}`}>
                      {selectedViolation.description}
                    </p>
                    <div className="flex items-center gap-2 flex-wrap">
                      <div className="flex items-center gap-3">
                        <span className={`text-xs ${isDark ? 'text-gray-400' : 'text-gray-500'}`}>
                          Score: <strong className="text-red-600">{selectedViolation.scoreImpact}</strong>
                        </span>
                        {selectedViolation.fineAmount > 0 && (
                          <span className={`text-xs ${isDark ? 'text-gray-400' : 'text-gray-500'}`}>
                            Fine: <strong className="text-red-600">£{selectedViolation.fineAmount}</strong>
                            ({FINE_STATUS_CONFIG[selectedViolation.fineStatus].label})
                          </span>
                        )}
                        {selectedViolation.dashcamEventId && (
                          <span className="text-xs bg-blue-50 text-blue-700 px-2 py-0.5 rounded-full font-medium">
                            📷 DashCam footage: {selectedViolation.dashcamEventId}
                          </span>
                        )}
                      </div>
                      {selectedViolation.reviewNote && (
                        <span className={`text-xs ${isDark ? 'text-gray-400' : 'text-gray-500'}`}>
                          Note: {selectedViolation.reviewNote}
                        </span>
                      )}
                      {selectedViolation.reviewStatus === 'pending' && (
                        <div className="flex gap-1.5 ml-auto">
                          <button className="text-xs bg-green-600 text-white px-3 py-1.5 rounded-lg font-medium">
                            Mark Reviewed
                          </button>
                          <button className="text-xs bg-red-600 text-white px-3 py-1.5 rounded-lg font-medium">
                            Raise Fine
                          </button>
                        </div>
                      )}
                    </div>
                  </div>
                )}

                <div className={`px-4 py-3 border-t text-xs flex items-center justify-between
                  ${isDark ? 'border-gray-700 text-gray-400' : 'border-gray-100 text-gray-500'}`}>
                  <span>Showing {filtered.length} of {violations.length} violations</span>
                  <span>Click row to see details · Click map pin to highlight</span>
                </div>
              </div>
            </div>
          </>
        )}

        {/* ── FINES & PENALTIES TAB ─────────────────────────────────────────── */}
        {activeTab === 'fines' && (
          <>
            {/* Fines KPIs */}
            <div className="grid grid-cols-4 gap-4 mb-5">
              {[
                { label: 'Total Fines', value: `£${totalFines.toLocaleString()}`, color: 'text-purple-600', bg: 'bg-purple-50' },
                { label: 'Pending Payment', value: `£${violations.filter(v => v.fineStatus === 'pending').reduce((a, v) => a + v.fineAmount, 0).toLocaleString()}`, color: 'text-amber-600', bg: 'bg-amber-50' },
                { label: 'Paid', value: `£${violations.filter(v => v.fineStatus === 'paid').reduce((a, v) => a + v.fineAmount, 0).toLocaleString()}`, color: 'text-green-600', bg: 'bg-green-50' },
                { label: 'Disputed/Appealed', value: violations.filter(v => ['disputed', 'appealed'].includes(v.fineStatus)).length, color: 'text-blue-600', bg: 'bg-blue-50' },
              ].map((kpi, i) => (
                <div key={i} className={`border rounded-2xl p-4 ${isDark ? 'bg-gray-800 border-gray-700' : 'bg-white border-gray-200'}`}>
                  <div className={`w-8 h-8 rounded-xl ${kpi.bg} flex items-center justify-center mb-2`}>
                    <DollarSign size={16} className={kpi.color} />
                  </div>
                  <p className={`text-xl font-bold ${isDark ? 'text-white' : 'text-gray-900'}`}>{kpi.value}</p>
                  <p className={`text-xs ${isDark ? 'text-gray-400' : 'text-gray-500'}`}>{kpi.label}</p>
                </div>
              ))}
            </div>

            {/* Fines table */}
            <div className={`rounded-2xl border overflow-hidden ${isDark ? 'bg-gray-800 border-gray-700' : 'bg-white border-gray-200'}`}>
              {/* DEVELOPER NOTE:
                  GET /api/fleetpoint/violations?fineStatus=pending,paid,disputed,appealed
                  PATCH /api/fleetpoint/violations/:id/fine
                  Body: { fineStatus: 'paid'|'disputed'|'appealed', paidAt, receiptUrl }
              */}
              <table className="w-full text-sm">
                <thead>
                  <tr className={`border-b text-xs font-semibold uppercase tracking-wide
                    ${isDark ? 'border-gray-700 bg-gray-900 text-gray-400' : 'border-gray-100 bg-gray-50 text-gray-500'}`}>
                    <th className="px-4 py-3 text-left">Violation</th>
                    <th className="px-4 py-3 text-left">Driver</th>
                    <th className="px-4 py-3 text-left">Vehicle</th>
                    <th className="px-4 py-3 text-left">Fine Amount</th>
                    <th className="px-4 py-3 text-left">Due Date</th>
                    <th className="px-4 py-3 text-left">Status</th>
                    <th className="px-4 py-3 text-left">Actions</th>
                  </tr>
                </thead>
                <tbody>
                  {violations.filter(v => v.fineAmount > 0).map(v => {
                    const fine = FINE_STATUS_CONFIG[v.fineStatus]
                    const isOverdue = v.fineDueDate && new Date(v.fineDueDate) < new Date() && v.fineStatus === 'pending'
                    return (
                      <tr key={v.id}
                        className={`border-b ${isDark ? 'border-gray-700' : 'border-gray-50'}
                          ${isOverdue ? (isDark ? 'bg-red-900/10' : 'bg-red-50/50') : ''}`}>
                        <td className="px-4 py-3">
                          <p className={`text-xs font-semibold ${isDark ? 'text-white' : 'text-gray-900'}`}>{v.type}</p>
                          <p className={`text-xs ${isDark ? 'text-gray-500' : 'text-gray-400'}`}>{v.id}</p>
                        </td>
                        <td className="px-4 py-3">
                          <span className={`text-xs ${isDark ? 'text-gray-300' : 'text-gray-700'}`}>{v.driverName}</span>
                        </td>
                        <td className="px-4 py-3">
                          <span className={`text-xs font-medium ${isDark ? 'text-purple-400' : 'text-purple-600'}`}>
                            {v.vehiclePlate}
                          </span>
                        </td>
                        <td className="px-4 py-3">
                          <span className="text-sm font-bold text-red-600">£{v.fineAmount.toLocaleString()}</span>
                        </td>
                        <td className="px-4 py-3">
                          <span className={`text-xs ${isOverdue ? 'text-red-600 font-bold' : isDark ? 'text-gray-400' : 'text-gray-500'}`}>
                            {v.fineDueDate || '—'}
                            {isOverdue && ' ⚠️ Overdue'}
                          </span>
                        </td>
                        <td className="px-4 py-3">
                          <span className={`text-xs px-2 py-0.5 rounded-full font-medium ${fine.color} ${fine.bg}`}>
                            {fine.label}
                          </span>
                        </td>
                        <td className="px-4 py-3">
                          <div className="flex items-center gap-1">
                            {v.fineStatus === 'pending' && (
                              <>
                                <button className="text-xs bg-green-600 hover:bg-green-700 text-white px-2.5 py-1.5 rounded-lg font-medium transition-colors">
                                  Mark Paid
                                </button>
                                <button className="text-xs bg-blue-600 hover:bg-blue-700 text-white px-2.5 py-1.5 rounded-lg font-medium transition-colors">
                                  Dispute
                                </button>
                              </>
                            )}
                            {v.fineStatus === 'paid' && (
                              <span className="text-xs text-green-600 font-medium">✓ Settled</span>
                            )}
                          </div>
                        </td>
                      </tr>
                    )
                  })}
                </tbody>
              </table>
            </div>
          </>
        )}

        {/* ── CONFIGURATION TAB ─────────────────────────────────────────────── */}
        {activeTab === 'config' && (
          <>
            {/* Config note */}
            <div className={`rounded-2xl p-4 mb-5 flex items-start gap-3
              ${isDark ? 'bg-blue-900/20 border border-blue-800' : 'bg-blue-50 border border-blue-200'}`}>
              <Settings size={16} className="text-blue-500 mt-0.5 shrink-0" />
              <div>
                <p className={`text-sm font-semibold ${isDark ? 'text-blue-300' : 'text-blue-800'}`}>
                  Violation Thresholds & Rules
                </p>
                <p className={`text-xs mt-0.5 ${isDark ? 'text-blue-400' : 'text-blue-700'}`}>
                  Configure speed thresholds, behaviour limits, and active violation types per fleet.
                  Fleet-level config overrides global default.
                  Changes take effect on the next telematics processing cycle.
                </p>
                {/* DEVELOPER NOTE:
                    GET /api/fleetpoint/violations/config — load current config
                    PUT /api/fleetpoint/violations/config — save updated config
                    Body: { fleetId, ...thresholds }
                    Backend validates and stores in violation_config table
                    Telematics pipeline reads config on startup + caches in Redis
                    Cache TTL: 5 minutes — config changes take up to 5 min to apply
                */}
              </div>
            </div>

            {/* Fleet selector */}
            <div className="flex items-center gap-3 mb-5">
              <label className={`text-sm font-medium ${isDark ? 'text-gray-300' : 'text-gray-700'}`}>
                Configure for:
              </label>
              <div className="flex gap-2">
                {violationConfigs.map(cfg => (
                  <button key={cfg.fleetId}
                    onClick={() => setActiveConfigFleet(cfg.fleetId)}
                    className={`px-3 py-2 rounded-xl text-xs font-medium border transition-all
                      ${activeConfigFleet === cfg.fleetId
                        ? 'bg-purple-600 text-white border-purple-600'
                        : `${isDark ? 'border-gray-700 text-gray-300 hover:bg-gray-800' : 'border-gray-200 text-gray-600 hover:bg-gray-50'}`}`}>
                    {cfg.fleetName}
                  </button>
                ))}
              </div>
            </div>

            <div className="grid grid-cols-2 gap-5">

              {/* Speed thresholds */}
              <div className={`rounded-2xl border p-5 ${isDark ? 'bg-gray-800 border-gray-700' : 'bg-white border-gray-200'}`}>
                <div className="flex items-center gap-2 mb-4">
                  <Zap size={16} className="text-red-500" />
                  <h3 className={`font-bold text-sm ${isDark ? 'text-white' : 'text-gray-900'}`}>
                    Speed Thresholds
                  </h3>
                </div>
                <div className="flex flex-col gap-4">
                  {[
                    { label: 'Alert (amber)', key: 'speedAlertKph', value: activeConfig.speedAlertKph, desc: 'Approaching limit — driver notified' },
                    { label: 'Violation (red)', key: 'speedViolationKph', value: activeConfig.speedViolationKph, desc: 'Limit exceeded — violation created' },
                    { label: 'Critical', key: 'speedCriticalKph', value: activeConfig.speedCriticalKph, desc: 'Significantly over — immediate alert' },
                  ].map(item => (
                    <div key={item.key}>
                      <div className="flex items-center justify-between mb-1">
                        <label className={`text-xs font-medium ${isDark ? 'text-gray-300' : 'text-gray-700'}`}>
                          {item.label}
                        </label>
                        <span className={`text-xs ${isDark ? 'text-gray-500' : 'text-gray-400'}`}>{item.desc}</span>
                      </div>
                      <div className="flex items-center gap-3">
                        <input type="number" defaultValue={item.value}
                          className={`w-24 border rounded-xl px-3 py-2 text-sm outline-none focus:border-purple-500
                            ${isDark ? 'bg-gray-700 border-gray-600 text-white' : 'bg-white border-gray-200 text-gray-700'}`} />
                        <span className={`text-xs ${isDark ? 'text-gray-400' : 'text-gray-500'}`}>km/h</span>
                        <div className={`flex-1 h-2 rounded-full overflow-hidden ${isDark ? 'bg-gray-700' : 'bg-gray-100'}`}>
                          <div className="h-full rounded-full"
                            style={{
                              width: `${(item.value / 160) * 100}%`,
                              background: item.key === 'speedAlertKph' ? '#f59e0b'
                                : item.key === 'speedViolationKph' ? '#ef4444' : '#7f1d1d'
                            }} />
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              </div>

              {/* Behaviour thresholds */}
              <div className={`rounded-2xl border p-5 ${isDark ? 'bg-gray-800 border-gray-700' : 'bg-white border-gray-200'}`}>
                <div className="flex items-center gap-2 mb-4">
                  <Car size={16} className="text-amber-500" />
                  <h3 className={`font-bold text-sm ${isDark ? 'text-white' : 'text-gray-900'}`}>
                    Behaviour Thresholds
                  </h3>
                </div>
                <div className="flex flex-col gap-4">
                  {[
                    { label: 'Harsh Braking', key: 'harshBrakingG', value: activeConfig.harshBrakingG, unit: 'g-force', desc: 'Deceleration threshold' },
                    { label: 'Harsh Acceleration', key: 'harshAccelerationG', value: activeConfig.harshAccelerationG, unit: 'g-force', desc: 'Acceleration threshold' },
                    { label: 'Harsh Cornering', key: 'harshCorneringG', value: activeConfig.harshCorneringG, unit: 'g-force', desc: 'Lateral g-force threshold' },
                    { label: 'Idling Limit', key: 'idlingMinutes', value: activeConfig.idlingMinutes, unit: 'minutes', desc: 'Engine on, vehicle stationary' },
                  ].map(item => (
                    <div key={item.key} className="flex items-center gap-3">
                      <div className="flex-1">
                        <label className={`text-xs font-medium ${isDark ? 'text-gray-300' : 'text-gray-700'}`}>
                          {item.label}
                        </label>
                        <p className={`text-xs ${isDark ? 'text-gray-500' : 'text-gray-400'}`}>{item.desc}</p>
                      </div>
                      <input type="number" step="0.05" defaultValue={item.value}
                        className={`w-20 border rounded-xl px-3 py-2 text-sm outline-none focus:border-purple-500
                          ${isDark ? 'bg-gray-700 border-gray-600 text-white' : 'bg-white border-gray-200 text-gray-700'}`} />
                      <span className={`text-xs w-14 ${isDark ? 'text-gray-400' : 'text-gray-500'}`}>{item.unit}</span>
                    </div>
                  ))}
                </div>
              </div>

              {/* Active violation types */}
              <div className={`rounded-2xl border p-5 ${isDark ? 'bg-gray-800 border-gray-700' : 'bg-white border-gray-200'}`}>
                <div className="flex items-center gap-2 mb-4">
                  <ToggleRight size={16} className="text-purple-500" />
                  <h3 className={`font-bold text-sm ${isDark ? 'text-white' : 'text-gray-900'}`}>
                    Active Violation Types
                  </h3>
                </div>
                <div className="flex flex-col gap-3">
                  {[
                    { label: 'Speeding', key: 'speedEnabled', value: activeConfig.speedEnabled },
                    { label: 'Harsh Braking', key: 'harshBrakingEnabled', value: activeConfig.harshBrakingEnabled },
                    { label: 'Harsh Acceleration', key: 'harshAccelerationEnabled', value: activeConfig.harshAccelerationEnabled },
                    { label: 'Harsh Cornering', key: 'harshCorneringEnabled', value: activeConfig.harshCorneringEnabled },
                    { label: 'Idling', key: 'idlingEnabled', value: activeConfig.idlingEnabled },
                    { label: 'Mobile Phone Use', key: 'mobileUseEnabled', value: activeConfig.mobileUseEnabled },
                    { label: 'Seatbelt', key: 'seatbeltEnabled', value: activeConfig.seatbeltEnabled },
                    { label: 'Geozone Violations', key: 'geozoneEnabled', value: activeConfig.geozoneEnabled },
                  ].map(item => (
                    <div key={item.key} className="flex items-center justify-between">
                      <span className={`text-xs font-medium ${isDark ? 'text-gray-300' : 'text-gray-700'}`}>
                        {item.label}
                      </span>
                      <button className={`flex items-center gap-1.5 px-3 py-1.5 rounded-xl text-xs font-medium transition-colors
                        ${item.value
                          ? 'bg-green-50 text-green-700 border border-green-200'
                          : `${isDark ? 'bg-gray-700 text-gray-400 border border-gray-600' : 'bg-gray-100 text-gray-500 border border-gray-200'}`}`}>
                        {item.value
                          ? <><ToggleRight size={12} /> Active</>
                          : <><ToggleLeft size={12} /> Inactive</>
                        }
                      </button>
                    </div>
                  ))}
                </div>
              </div>

              {/* Working hours config */}
              <div className={`rounded-2xl border p-5 ${isDark ? 'bg-gray-800 border-gray-700' : 'bg-white border-gray-200'}`}>
                <div className="flex items-center gap-2 mb-4">
                  <Clock size={16} className="text-blue-500" />
                  <h3 className={`font-bold text-sm ${isDark ? 'text-white' : 'text-gray-900'}`}>
                    Working Hours & Compliance
                  </h3>
                </div>
                <div className="flex flex-col gap-4">
                  <div className="flex items-center justify-between">
                    <div>
                      <p className={`text-xs font-medium ${isDark ? 'text-gray-300' : 'text-gray-700'}`}>
                        Out-of-Hours Driving
                      </p>
                      <p className={`text-xs ${isDark ? 'text-gray-500' : 'text-gray-400'}`}>
                        Alert when driving outside shift hours
                      </p>
                    </div>
                    <button className={`text-xs px-3 py-1.5 rounded-xl font-medium border
                      ${activeConfig.drivingOutsideHoursEnabled
                        ? 'bg-green-50 text-green-700 border-green-200'
                        : 'bg-gray-100 text-gray-500 border-gray-200'}`}>
                      {activeConfig.drivingOutsideHoursEnabled ? '✓ Enabled' : 'Disabled'}
                    </button>
                  </div>
                  <div className="grid grid-cols-2 gap-3">
                    <div>
                      <label className={`block text-xs font-medium mb-1 ${isDark ? 'text-gray-300' : 'text-gray-700'}`}>
                        Shift Start
                      </label>
                      <input type="time" defaultValue={activeConfig.shiftStartTime}
                        className={`w-full border rounded-xl px-3 py-2 text-sm outline-none
                          ${isDark ? 'bg-gray-700 border-gray-600 text-white' : 'bg-white border-gray-200 text-gray-700'}`} />
                    </div>
                    <div>
                      <label className={`block text-xs font-medium mb-1 ${isDark ? 'text-gray-300' : 'text-gray-700'}`}>
                        Shift End
                      </label>
                      <input type="time" defaultValue={activeConfig.shiftEndTime}
                        className={`w-full border rounded-xl px-3 py-2 text-sm outline-none
                          ${isDark ? 'bg-gray-700 border-gray-600 text-white' : 'bg-white border-gray-200 text-gray-700'}`} />
                    </div>
                  </div>
                  <div className="flex items-center justify-between">
                    <div>
                      <p className={`text-xs font-medium ${isDark ? 'text-gray-300' : 'text-gray-700'}`}>
                        Geozone Violations
                      </p>
                      <p className={`text-xs ${isDark ? 'text-gray-500' : 'text-gray-400'}`}>
                        Alert on restricted zone entry
                      </p>
                    </div>
                    <button className={`text-xs px-3 py-1.5 rounded-xl font-medium border
                      ${activeConfig.geozoneViolationsEnabled
                        ? 'bg-green-50 text-green-700 border-green-200'
                        : 'bg-gray-100 text-gray-500 border-gray-200'}`}>
                      {activeConfig.geozoneViolationsEnabled ? '✓ Enabled' : 'Disabled'}
                    </button>
                  </div>
                </div>
              </div>
            </div>

            {/* Save button */}
            <div className="flex justify-end mt-4">
              <button className="flex items-center gap-2 bg-purple-600 hover:bg-purple-700 text-white font-semibold px-6 py-3 rounded-xl transition-colors">
                <CheckCircle size={16} /> Save Configuration
              </button>
            </div>
          </>
        )}
      </div>

      {/* Add Manual Violation Modal */}
      {showCreateModal && (
        <div className="fixed inset-0 z-[9999] flex items-center justify-center bg-black/60 backdrop-blur-md">
          <div className={`rounded-3xl shadow-2xl w-full max-w-lg mx-4 p-6 ${isDark ? 'bg-gray-900' : 'bg-white'}`}>
            <div className="flex items-center justify-between mb-5">
              <h2 className={`font-bold text-lg ${isDark ? 'text-white' : 'text-gray-900'}`}>
                Add Manual Violation
              </h2>
              <button onClick={() => setShowCreateModal(false)} className="text-gray-400 hover:text-gray-600">
                <X size={20} />
              </button>
            </div>
            {/* DEVELOPER NOTE:
                POST /api/fleetpoint/violations
                Body: { vehicleId, driverId, source: 'manual', type, category, severity,
                        description, fineAmount, fineDueDate, timestamp }
                On success: add to local state, close modal, show toast
            */}
            <div className="flex flex-col gap-3">
              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className={`block text-xs font-medium mb-1 ${isDark ? 'text-gray-300' : 'text-gray-700'}`}>
                    Driver *
                  </label>
                  <select className={`w-full border rounded-xl px-3 py-2.5 text-sm outline-none
                    ${isDark ? 'bg-gray-800 border-gray-700 text-white' : 'bg-white border-gray-200 text-gray-700'}`}>
                    <option value="">Select driver...</option>
                    {drivers.map(d => <option key={d.id} value={d.id}>{d.name}</option>)}
                  </select>
                </div>
                <div>
                  <label className={`block text-xs font-medium mb-1 ${isDark ? 'text-gray-300' : 'text-gray-700'}`}>
                    Category *
                  </label>
                  <select className={`w-full border rounded-xl px-3 py-2.5 text-sm outline-none
                    ${isDark ? 'bg-gray-800 border-gray-700 text-white' : 'bg-white border-gray-200 text-gray-700'}`}>
                    {Object.entries(CATEGORY_CONFIG).map(([val, cfg]) => (
                      <option key={val} value={val}>{cfg.label}</option>
                    ))}
                  </select>
                </div>
              </div>
              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className={`block text-xs font-medium mb-1 ${isDark ? 'text-gray-300' : 'text-gray-700'}`}>
                    Violation Type *
                  </label>
                  <input placeholder="e.g. MOT Expired, Licence Issue..."
                    className={`w-full border rounded-xl px-3 py-2.5 text-sm outline-none focus:border-purple-500
                      ${isDark ? 'bg-gray-800 border-gray-700 text-white placeholder-gray-500' : 'bg-white border-gray-200 text-gray-900 placeholder-gray-400'}`} />
                </div>
                <div>
                  <label className={`block text-xs font-medium mb-1 ${isDark ? 'text-gray-300' : 'text-gray-700'}`}>
                    Severity *
                  </label>
                  <select className={`w-full border rounded-xl px-3 py-2.5 text-sm outline-none
                    ${isDark ? 'bg-gray-800 border-gray-700 text-white' : 'bg-white border-gray-200 text-gray-700'}`}>
                    {Object.entries(SEVERITY_CONFIG).map(([val, cfg]) => (
                      <option key={val} value={val}>{cfg.label}</option>
                    ))}
                  </select>
                </div>
              </div>
              <div>
                <label className={`block text-xs font-medium mb-1 ${isDark ? 'text-gray-300' : 'text-gray-700'}`}>
                  Description *
                </label>
                <textarea rows={2} placeholder="Describe the violation..."
                  className={`w-full border rounded-xl px-3 py-2.5 text-sm outline-none focus:border-purple-500 resize-none
                    ${isDark ? 'bg-gray-800 border-gray-700 text-white placeholder-gray-500' : 'bg-white border-gray-200 text-gray-900 placeholder-gray-400'}`} />
              </div>
              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className={`block text-xs font-medium mb-1 ${isDark ? 'text-gray-300' : 'text-gray-700'}`}>
                    Fine Amount (£)
                  </label>
                  <input type="number" placeholder="0 if no fine"
                    className={`w-full border rounded-xl px-3 py-2.5 text-sm outline-none
                      ${isDark ? 'bg-gray-800 border-gray-700 text-white placeholder-gray-500' : 'bg-white border-gray-200 text-gray-700 placeholder-gray-400'}`} />
                </div>
                <div>
                  <label className={`block text-xs font-medium mb-1 ${isDark ? 'text-gray-300' : 'text-gray-700'}`}>
                    Fine Due Date
                  </label>
                  <input type="date"
                    className={`w-full border rounded-xl px-3 py-2.5 text-sm outline-none
                      ${isDark ? 'bg-gray-800 border-gray-700 text-white' : 'bg-white border-gray-200 text-gray-700'}`} />
                </div>
              </div>
            </div>
            <div className="flex gap-2 mt-5">
              <button onClick={() => setShowCreateModal(false)}
                className={`flex-1 py-2.5 rounded-xl text-sm font-medium border
                  ${isDark ? 'border-gray-700 text-gray-300' : 'border-gray-200 text-gray-600'}`}>
                Cancel
              </button>
              <button onClick={() => setShowCreateModal(false)}
                className="flex-1 py-2.5 rounded-xl text-sm font-semibold bg-purple-600 hover:bg-purple-700 text-white transition-colors">
                Add Violation
              </button>
            </div>
          </div>
        </div>
      )}
    </FleetpointLayout>
  )
}
