export type DeviceStatus='active'|'faulty'|'in-stock'|'installed'|'uninstalled';
export type DeviceCategory='gps-tracker'|'dashcam'|'temp-sensor'|'fuel-sensor'|'rfid-reader'|'eye-sensor';
export interface DeviceRecord{id:string;name:string;category:DeviceCategory;manufacturer:string;model:string;imei:string;serial:string;status:DeviceStatus;vehicle:string;vehicleModel:string;signal:number;battery:number;firmware:string;lastPing:string;warranty:string;notes:string}
export const DEVICES:DeviceRecord[]=[
{id:'D001',name:'GPS Tracker 4821',category:'gps-tracker',manufacturer:'Teltonika',model:'FMB140',imei:'352093081204821',serial:'GPS-4821-A',status:'active',vehicle:'LP-4821',vehicleModel:'Volvo FH',signal:92,battery:86,firmware:'03.29.00',lastPing:'2 min ago',warranty:'18 months',notes:''},
{id:'D002',name:'Front DashCam',category:'dashcam',manufacturer:'VisionTrack',model:'VT2000',imei:'868312040004821',serial:'DC-4821-F',status:'active',vehicle:'LP-4821',vehicleModel:'Volvo FH',signal:84,battery:100,firmware:'5.8.2',lastPing:'3 min ago',warranty:'12 months',notes:''},
{id:'D003',name:'RFID Reader',category:'rfid-reader',manufacturer:'Identiv',model:'uTrust',imei:'—',serial:'RFID-4821',status:'active',vehicle:'LP-4821',vehicleModel:'Volvo FH',signal:78,battery:72,firmware:'2.3.1',lastPing:'4 min ago',warranty:'20 months',notes:''},
{id:'D004',name:'GPS Tracker 9901',category:'gps-tracker',manufacturer:'Teltonika',model:'FMB920',imei:'352093081209901',serial:'GPS-9901-A',status:'faulty',vehicle:'LP-9901',vehicleModel:'Volvo FH',signal:0,battery:12,firmware:'03.27.01',lastPing:'2 hours ago',warranty:'4 months',notes:'Intermittent power'},
{id:'D005',name:'GPS Tracker 0392',category:'gps-tracker',manufacturer:'Queclink',model:'GV300',imei:'352093081200392',serial:'GPS-0392',status:'active',vehicle:'LP-0392',vehicleModel:'Volvo FH Reefer',signal:72,battery:68,firmware:'4.1.0',lastPing:'6 min ago',warranty:'9 months',notes:''},
{id:'D006',name:'Temperature Sensor',category:'temp-sensor',manufacturer:'Sensitech',model:'TempTale',imei:'—',serial:'TEMP-0392',status:'faulty',vehicle:'LP-0392',vehicleModel:'Volvo FH Reefer',signal:18,battery:24,firmware:'1.9.4',lastPing:'48 min ago',warranty:'Expired',notes:'Calibration required'},
{id:'D007',name:'Rear DashCam',category:'dashcam',manufacturer:'VisionTrack',model:'VT2000',imei:'868312040000392',serial:'DC-0392-R',status:'active',vehicle:'LP-0392',vehicleModel:'Volvo FH Reefer',signal:66,battery:100,firmware:'5.8.2',lastPing:'7 min ago',warranty:'11 months',notes:''},
{id:'D008',name:'Fuel Sensor',category:'fuel-sensor',manufacturer:'Escort',model:'TD-BLE',imei:'—',serial:'FUEL-2201',status:'in-stock',vehicle:'',vehicleModel:'',signal:0,battery:100,firmware:'2.0.0',lastPing:'Never',warranty:'24 months',notes:'Warehouse A'},
{id:'D009',name:'Eye Sensor',category:'eye-sensor',manufacturer:'Seeing Machines',model:'Guardian',imei:'—',serial:'EYE-5531',status:'in-stock',vehicle:'',vehicleModel:'',signal:0,battery:100,firmware:'7.1.2',lastPing:'Never',warranty:'18 months',notes:'Ready to install'},
];
export const CATEGORY_LABELS:Record<DeviceCategory,string>={'gps-tracker':'GPS Tracker',dashcam:'DashCam','temp-sensor':'Temp Sensor','fuel-sensor':'Fuel Sensor','rfid-reader':'RFID Reader','eye-sensor':'Eye/Fatigue Sensor'};
