export const environment = {
  production: true,
  apiBaseUrl: 'https://devgateway.hypernymbiz.com',
  userMsBaseUrl: 'https://devgateway.hypernymbiz.com/user-ms',
  cobPackagesBaseUrl: 'https://devgateway.hypernymbiz.com/cob-packages',
  cobConsumerAppSecret: 'G;6{l?5]V@p5@2~<f%PFJ+W4k@-H?s',
  fleetBaseUrl: 'https://devgateway.hypernymbiz.com/fms-fleet',
  signalRUrl: 'https://func-vfq-dev.azurewebsites.net',
  useCaseId: 6,
  firebase: {
    apiKey: 'AIzaSyDybdUp0Ue3yuPS5XQfGMxXeBq0CzQ-cME',
    authDomain: 'fmsnewpackage.firebaseapp.com',
    databaseURL: 'https://fmsnewpackage-default-rtdb.firebaseio.com',
    projectId: 'fmsnewpackage',
    storageBucket: 'fmsnewpackage.appspot.com',
    messagingSenderId: '1076830721170',
    appId: '1:1076830721170:web:b72455693f5aa3cfd1024b',
    measurementId: 'G-FV991JH40G',
  },
} as const;
